# Generated by Django 5.0.7 on 2024-07-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0003_alter_result_exam"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionoption",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
