# Generated by Django 5.0.7 on 2024-07-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0004_alter_questionoption_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
