# Generated by Django 5.0.7 on 2024-09-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0007_alter_answer_question_alter_answer_selected_option_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="score",
            name="rank",
            field=models.CharField(
                choices=[
                    ("gold", "طلایی"),
                    ("silver", "نقره ای"),
                    ("bronze", "برنز"),
                    ("unranked", "بدون رنک"),
                ],
                default="unranked",
                max_length=20,
            ),
        ),
    ]
