# Generated by Django 5.0.7 on 2024-07-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=255, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "ادمین"),
                            ("instructor", "مربی"),
                            ("student", "دانش اموز"),
                        ],
                        max_length=20,
                        verbose_name="نقش",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "joined_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ عضویت"),
                ),
            ],
            options={
                "verbose_name": "کاربران",
            },
        ),
    ]
